In [1]:
import requests
import json
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import psycopg2

In [22]:
pip install psycopg2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2 in c:\users\catch\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.9.9)
Note: you may need to restart the kernel to use updated packages.

In [23]:
!git clone https://github.com/PhonePe/pulse.git

fatal: destination path 'pulse' already exists and is not an empty directory.

In [68]:
#Agg_Trans

input_path="C:/Users/catch/OneDrive/Desktop/phone pay/pulse/data/aggregated/Transaction/country/india/state/"
Agg_state_list=os.listdir(input_path)

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in Agg_state_list:
    ip=input_path+state+"/"
    Agg_yr=os.listdir(ip)
    for j in Agg_yr:
        p_j=ip+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(state)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Agg_Trans=pd.DataFrame(clm)
Agg_Trans.sort_values(by='State', inplace=True)
Agg_Trans['State']=Agg_Trans['State'].str.title()
Agg_Trans['State']=Agg_Trans['State'].str.replace("&",'and')
Agg_Trans['State']=Agg_Trans['State'].str.replace("-",' ')
Agg_Trans['State']=Agg_Trans['State'].str.replace("Andaman and Nicobar Islands",'Andaman & Nicobar')
Agg_Trans.sort_values(by=["Year","Quater"],inplace=True)
Agg_Trans.reset_index(drop=True, inplace=True)

In [55]:
A=Agg_Trans['Year'].unique()
B=sorted(A)
Agg_Trans.reset_index(drop=True, inplace=True)

In [2]:
#Agg_User


input_path2="C:/Users/catch/OneDrive/Desktop/phone pay/pulse/data/aggregated/user/country/india/state/"
Agg_User_list=os.listdir(input_path2)
clm={'State':[], 'Year':[],'Quater':[],'Brands':[], 'Transacion_count':[], 'Percentage':[]}

for state in Agg_User_list:
    ip=input_path2+state+"/"
    Agg_yr=os.listdir(ip)
    for j in Agg_yr:
        p_j=ip+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            E=json.load(Data)
            try:
              for z in E['data']['usersByDevice']:


                brand=z['brand']
                count=z['count']
                percentage=z['percentage']
                clm['Brands'].append(brand)
                clm['Transacion_count'].append(count)
                clm['Percentage'].append(percentage)
                clm['State'].append(state)
                clm['Year'].append(j)
                clm['Quater'].append(int(k.strip('.json')))

            except:
              pass


Agg_User=pd.DataFrame(clm)
Agg_User.sort_values(by='State', inplace=True)
Agg_User['State']=Agg_User['State'].str.title()
Agg_User['State']=Agg_User['State'].str.replace("&",'and')
Agg_User['State']=Agg_User['State'].str.replace("-",' ')
Agg_User['State']=Agg_User['State'].str.replace("Andaman and Nicobar Islands",'Andaman & Nicobar')
Agg_User.sort_values(by=["Year","Quater"],inplace=True)
Agg_User.reset_index(drop=True, inplace=True)

In [71]:
#map_Trans

input_path3="C:/Users/catch/OneDrive/Desktop/phone pay/pulse/data/map/Transaction/hover/country/india/state/"
Trans_list=os.listdir(input_path3)
clm={'State':[], 'Year':[],'Quater':[],'Districts':[], 'Transacion_count':[], 'Amount':[]}

for state in Trans_list:
    ip=input_path3+state+"/"
    Agg_yr=os.listdir(ip)
    for j in Agg_yr:
        p_j=ip+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            F=json.load(Data)
            for z in F['data']['hoverDataList']:


              name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              clm['Districts'].append(name)
              clm['Transacion_count'].append(count)
              clm['Amount'].append(amount)
              clm['State'].append(state)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))

Map_Trans=pd.DataFrame(clm)
Map_Trans.sort_values(by='State', inplace=True)
Map_Trans['Districts']=Map_Trans['Districts'].str.title()
Map_Trans['Districts']=Map_Trans['Districts'].str.replace("District",'')
Map_Trans['State']=Map_Trans['State'].str.title()
Map_Trans['State']=Map_Trans['State'].str.replace("&",'and')
Map_Trans['State']=Map_Trans['State'].str.replace("-",' ')
Map_Trans['State']=Map_Trans['State'].str.replace("Andaman and Nicobar Islands",'Andaman & Nicobar')
Map_Trans.sort_values(by=["Year","Quater"],inplace=True)
Map_Trans.reset_index(drop=True, inplace=True)

In [73]:
#map_user

input_path4="C:/Users/catch/OneDrive/Desktop/phone pay/pulse/data/map/user/hover/country/india/state/"
Trans_list=os.listdir(input_path4)
clm={'State':[], 'Year':[],'Quater':[],'Districts':[], 'RegisteredUser':[], 'Appopens':[]}

for state in Trans_list:
    ip=input_path4+state+"/"
    Agg_yr=os.listdir(ip)
    for j in Agg_yr:
        p_j=ip+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            E=json.load(Data)
            for z in E['data']['hoverData'].items():
              Districts=z[0]
              RegUsers=z[1]['registeredUsers']
              Appopen=z[1]['appOpens']
              clm['Districts'].append(Districts)
              clm['RegisteredUser'].append(RegUsers)
              clm['Appopens'].append(Appopen)
              clm['State'].append(state)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))

Map_User=pd.DataFrame(clm)
Map_User.sort_values(by='State', inplace=True)
Map_User['Districts']=Map_User['Districts'].str.title()
Map_User['Districts']=Map_User['Districts'].str.replace("District",'')
Map_User['State']=Map_User['State'].str.title()
Map_User['State']=Map_User['State'].str.replace("&",'and')
Map_User['State']=Map_User['State'].str.replace("-",' ')
Map_User['State']=Map_User['State'].str.replace("Andaman and Nicobar Islands",'Andaman & Nicobar')
Map_User.sort_values(by=["Year","Quater"],inplace=True)
Map_User.reset_index(drop=True, inplace=True)

In [75]:
#Top_Trans
input_path5="C:/Users/catch/OneDrive/Desktop/phone pay/pulse/data/top/transaction/country/india/state/"
Top_User_list=os.listdir(input_path5)
clm={'State':[], 'Year':[],'Quater':[],'Pincode':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in Top_User_list:
    ip=input_path5+state+"/"
    Agg_yr=os.listdir(ip)
    for j in Agg_yr:
        p_j=ip+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            F=json.load(Data)
            for z in F['data']['pincodes']:
              entityname=z['entityName']
              count=z['metric']['count']
              amount=z['metric']['amount']
              clm['Pincode'].append(entityname)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(state)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))


Top_Trans=pd.DataFrame(clm)
Top_Trans.sort_values(by='State', inplace=True)
Top_Trans['State']=Top_Trans['State'].str.title()
Top_Trans['State']=Top_Trans['State'].str.replace("&",'and')
Top_Trans['State']=Top_Trans['State'].str.replace("-",' ')
Top_Trans['State']=Top_Trans['State'].str.replace("Andaman and Nicobar Islands",'Andaman & Nicobar')
Top_Trans.sort_values(by=["Year","Quater"],inplace=True)
Top_Trans.reset_index(drop=True, inplace=True)

In [76]:
#Top_User

input_path6="C:/Users/catch/OneDrive/Desktop/phone pay/pulse/data/top/user/country/india/state/"
Top_User_list=os.listdir(input_path6)
clm={'State':[], 'Year':[],'Quater':[],'Pincode':[], 'RegisteredUsers':[]}

for state in Top_User_list:
    ip=input_path6+state+"/"
    Agg_yr=os.listdir(ip)
    for j in Agg_yr:
        p_j=ip+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            G=json.load(Data)
            for z in G['data']['pincodes']:
              entityname=z['name']
              RegUsers=z['registeredUsers']
              clm['Pincode'].append(entityname)
              clm['RegisteredUsers'].append(RegUsers)
              clm['State'].append(state)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))


Top_User=pd.DataFrame(clm)

Top_User.sort_values(by='State', inplace=True)
Top_User['State']=Top_User['State'].str.title()
Top_User['State']=Top_User['State'].str.replace("&",'and')
Top_User['State']=Top_User['State'].str.replace("-",' ')
Top_User['State']=Top_User['State'].str.replace("Andaman and Nicobar Islands",'Andaman & Nicobar')
Top_User.sort_values(by=["Year","Quater"],inplace=True)
Top_User.reset_index(drop=True, inplace=True)

In [ ]:
# Agg_Trans

db=psycopg2.connect(host='localhost',user='postgres',password='11001100',database='phonepay',port=5432)
access=db.cursor()
db.commit()

drop= "drop table if exists Agg_Trans"
access.execute(drop)
db.commit()


access.execute('''create table if not exists Agg_Trans(State varchar(100),
                                                    Year int,                                                    
                                                    Quater int,
                                                    Transaction_type varchar(200),
                                                    Transaction_count bigint,
                                                    Transaction_amount bigint                                                                                                                             
                                                    )''')         
db.commit()


insert_query='''insert into Agg_Trans(State,
                                    Year,
                                    Quater,
                                    Transaction_type,
                                    Transaction_count,
                                    Transaction_amount)
                                    
                                    values(%s,%s,%s,%s,%s,%s)'''                                    
          

if not Agg_Trans.empty:   
    data = [tuple(row) for row in Agg_Trans.values]    
    access.executemany(insert_query, data)
    db.commit()
    print("Data inserted successfully.")
else:
    print("Agg_User DataFrame is empty.")


access.close()
db.close()

In [ ]:
#Agg_User
db=psycopg2.connect(host='localhost',user='postgres',password='11001100',database='phonepay',port=5432)
access=db.cursor()
db.commit()

drop= "drop table if exists Agg_User"
access.execute(drop)
db.commit()


access.execute('''create table if not exists Agg_User(State varchar(100),
                                                    Year int,                                                    
                                                    Quater int,
                                                    Brands varchar(200),
                                                    Transacion_count bigint,
                                                    Percentage float                                                                                                                             
                                                    )''')         
db.commit()


insert_query='''insert into Agg_User(State,
                                    Year,
                                    Quater,
                                    Brands,
                                    Transacion_count,
                                    Percentage)
                                    
                                    values(%s,%s,%s,%s,%s,%s)'''                                    
          

if not Agg_User.empty:   
    data = [tuple(row) for row in Agg_User.values]    
    access.executemany(insert_query, data)
    db.commit()
    print("Data inserted successfully.")
else:
    print("Agg_User DataFrame is empty.")


access.close()
db.close()

In [ ]:
#Map_Trans
db=psycopg2.connect(host='localhost',user='postgres',password='11001100',database='phonepay',port=5432)
access=db.cursor()
db.commit()


drop= "drop table if exists Map_Trans"
access.execute(drop)
db.commit()

access.execute('''create table if not exists Map_Trans(State varchar(100),
                                                    Year int,                                                    
                                                    Quater int,
                                                    Districts varchar(200),
                                                    Transacion_count bigint,
                                                    Amount bigint                                                                                                                             
                                                    )''')         
db.commit()


insert_query='''insert into Map_Trans(State,
                                    Year,
                                    Quater,
                                    Districts,
                                    Transacion_count,
                                    Amount)
                                    
                                    values(%s,%s,%s,%s,%s,%s)'''                                    
          

if not Map_Trans.empty:   
    data = [tuple(row) for row in Map_Trans.values]    
    access.executemany(insert_query, data)
    db.commit()
    print("Data inserted successfully.")
else:
    print("Agg_User DataFrame is empty.")


access.close()
db.close()

In [ ]:
#Map_User
db=psycopg2.connect(host='localhost',user='postgres',password='11001100',database='phonepay',port=5432)
access=db.cursor()
db.commit()

drop= "drop table if exists Map_User"
access.execute(drop)
db.commit()

access.execute('''create table if not exists Map_User(State varchar(100),
                                                    Year int,                                                    
                                                    Quater int,
                                                    Districts varchar(200),
                                                    RegisteredUser bigint,
                                                    Appopens bigint                                                                                                                             
                                                    )''')         
db.commit()


insert_query='''insert into Map_User(State,
                                    Year,
                                    Quater,
                                    Districts,
                                    RegisteredUser,
                                    Appopens)
                                    
                                    values(%s,%s,%s,%s,%s,%s)'''                                    
          

if not Map_User.empty:   
    data = [tuple(row) for row in Map_User.values]    
    access.executemany(insert_query, data)
    db.commit()
    print("Data inserted successfully.")
else:
    print("Map_User DataFrame is empty.")


access.close()
db.close()

In [ ]:
#Top_Trans
db=psycopg2.connect(host='localhost',user='postgres',password='11001100',database='phonepay',port=5432)
access=db.cursor()
db.commit()

drop= "drop table if exists Top_Trans"
access.execute(drop)
db.commit()

access.execute('''create table if not exists Top_Trans(State varchar(100),
                                                    Year int,                                                    
                                                    Quater int,
                                                    Pincode int,
                                                    Transacion_count bigint,
                                                    Transacion_amount bigint                                                                                                                             
                                                    )''')         
db.commit()


insert_query='''insert into Top_Trans(State,
                                    Year,
                                    Quater,
                                    Pincode,
                                    Transacion_count,
                                    Transacion_amount)
                                    
                                    values(%s,%s,%s,%s,%s,%s)'''                                    
          

if not Top_Trans.empty:   
    data = [tuple(row) for row in Top_Trans.values]    
    access.executemany(insert_query, data)
    db.commit()
    print("Data inserted successfully.")
else:
    print("Top_Trans DataFrame is empty.")


access.close()
db.close()

In [ ]:
#Top_User
db=psycopg2.connect(host='localhost',user='postgres',password='11001100',database='phonepay',port=5432)
access=db.cursor()
db.commit()

drop= "drop table if exists Top_User"
access.execute(drop)
db.commit()

access.execute('''create table if not exists Top_User(State varchar(100),
                                                    Year int,                                                    
                                                    Quater int,
                                                    Pincode int,
                                                    RegisteredUsers bigint
                                                                                                                                                                                
                                                    )''')         
db.commit()


insert_query='''insert into Top_User(State,
                                    Year,
                                    Quater,
                                    Pincode,                                    
                                    RegisteredUsers)
                                    
                                    values(%s,%s,%s,%s,%s)'''                                    
          

if not Top_User.empty:   
    data = [tuple(row) for row in Top_User.values]    
    access.executemany(insert_query, data)
    db.commit()
    print("Data inserted successfully.")
else:
    print("Top_User DataFrame is empty.")


access.close()
db.close()